server:
  port: 8081

spring:
  application:
    name: recruiter
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      fail-on-empty-beans: false
  graphql:
    path: /recruiter
    graphiql:
      enabled: true
      path: /graphiql
